core/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import SignUpView
handler404 = 'home.views.error_404'
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from home.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
app_name = "home"

urlpatterns = [
    path('', home, name="home"),
    path('profile', Profile.as_view(), name="profile"),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='home/change_password.html',
            success_url = '/accounts/logout/'
        ),
        name='change_password'
    ),
    path('destination_details/<str:destination_id>', destination_details, name="destination_details"),
    path('destination', destination, name="destination"),
    path('post_comment/<str:destination_id>', post_comment, name="post_comment"),
    path('delete_comment/<str:destination_id>/<str:comment_id>', delete_comment, name="delete_comment"),
    path('rate_destination/<str:destination_id>', post_rate, name="post_rate"),
    path('category', category, name="category"),
    path('search', search_destination, name="search_destination"),
    path('report_comment/<str:destination_id>/<str:comment_id>', report_comment, name="report_comment"),
    path('verify-email/<str:verification_token>', verify_email, name="verify_email"),
    path('reaction/<str:destination_id>/<str:reaction>', reaction, name="reaction"),
    path('content_creator', content_creator, name="content_creator"),
    path('about', about, name="about"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from home.models import User
from django.core.validators import ValidationError
from django import forms
from django.core.mail import send_mail
from util.Util import random_string_generator, send_email_generic
class SignUpForm(UserCreationForm):
   email = forms.EmailField(required=True,label='Email',error_messages={'exists': 'Oops! Email already exist'})
   class Meta:
      model = User 
      fields = ('username', 'email', 'password1', 'password2',)

   def save(self, commit=True):
        user = super().save(commit=False)
        clean_email = self.cleaned_data["email"]
        verification_token = random_string_generator(12)
        user.email = clean_email
        user.email_verification_token = verification_token
        if commit:
            user.save()
            # send email verification
            self.verify_email(clean_email, verification_token)
        return user

   def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise ValidationError(self.fields['email'].error_messages['exists'])
        return self.cleaned_data['email']

   def verify_email(self, email, token):
       url = "http://128.199.86.130:8000/verify-email/{}".format(token)
       msg = "<p>Thanks for signing up to MUSEO Tu' Agusan.</p>"
       msg += "<p>Please click the link below for emaiil verification.</p>"
       msg += "<p>&nbsp;</p>"
       msg += '<p><a href="{0}">{0}</a></p>'.format(url)
       msg += "<p>&nbsp;</p>"
       msg += "<p>Thanks</p>"
       send_email_generic(msg, email)

home/views.py
from django.core.mail import message
from home.forms import SignUpForm
from home.models import *
from util.Common import *


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


def error_404(request, exception):
    return render(request, 'home/404.html', {})


def home(request):
    featured = Featured.objects.all().order_by('-id')
    categories = Category.objects.all()
    payload = {
        'featured_destination': featured,
        'categories': categories
    }
    return render(request, 'home/home.html', payload)


def destination(request):
    destinations = Destination.objects.all().order_by('-id')
    filter = request.GET.get('category')
    if filter:
        category = get_object_or_404(Category, title=filter)
        destinations = Destination.objects.filter(category=category).order_by('-id')

    payload = {
        'destinations': destinations
    }
    return render(request, 'home/destination.html', payload)


def destination_details(request, destination_id):
    destination = get_object_or_404(Destination, pk=signer.unsign(destination_id))
    is_like = None
    if request.user.is_authenticated:
        is_like = destination.getIsLike(request.user)

    if request.method == "POST":
        like_action = request.POST.get('like_action')
        print(like_action)
        if not request.user.is_authenticated:
            return HttpResponse("Unauthorized")

        if like_action:
            if not is_like:
                destination.likes.add(request.user)
            else:
                destination.likes.remove(request.user)

        return HttpResponseRedirect(reverse('home:destination_details', kwargs={'destination_id': destination_id}))

    other_destinations = Destination.objects.exclude(pk=destination.pk).order_by('-id')[:10]
    other_photos = ""
    main_photo = destination.first_image
    if destination.photos.count() > 0:
        other_photos = destination.photos.all()[1:]
        other_photos = [p.photo for p in other_photos]
    payload = {
        'destination': destination,
        'other_destinations': other_destinations,
        'main_photo': main_photo,
        'other_photos': other_photos,
        'is_like': is_like
    }
    return render(request, 'home/destination_details.html', payload)


@method_decorator([], name='dispatch')
class Profile(View):
    template_name = "home/profile.html"

    def get(self, request, *args, **kwargs):
        if not request.user.get_name_is_empty():
            messages.warning(request, "Please complete your profile")

        profile_info = {}
        profile_info['First Name'] = {'value': request.user.first_name if request.user.first_name != "None" else "",
                                   'placeholder': "Enter First name"}
        profile_info['Last Name'] = {'value': request.user.last_name if request.user.last_name != "None" else "",
                                      'placeholder': "Enter Last name"}
        profile_info['Address'] = {'value': request.user.address if request.user.address != "None" else "", 'placeholder': "Enter Address"}
        profile_info['Email'] = {'value': request.user.email if request.user.email != "None" else "", 'placeholder': "Enter Email"}
        profile_info['Gender'] = {'value': request.user.gender if request.user.gender != "None" else "", 'placeholder': "Enter Gender (MALE/FEMALE)"}
        profile_info['Phone number'] = {'value': request.user.phone_number if request.user.phone_number != "None" else "", 'placeholder': "Enter phone number"}
        context = {
            'profile_info': profile_info
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        address = self.request.POST.get("Address")
        gender = request.POST.get("Gender")
        p_number = request.POST.get("Phone number")
        last_name = request.POST.get("Last Name")
        first_name = request.POST.get("First Name")
        if not gender.upper() in ["MALE", "FEMALE"]:
            messages.error(request, "Invalid Gender")
            return HttpResponseRedirect(reverse("home:profile"))

        if len(last_name) <= 0 or len(first_name) <= 0:
            messages.error(request, "First name and Last name must not be empty")
            return HttpResponseRedirect(reverse("home:profile"))

        user = get_object_or_404(User, pk=request.user.pk)
        user.address = address
        user.gender = gender.upper()
        user.phone_number = p_number
        user.last_name = last_name
        user.first_name = first_name
        user.save()
        messages.success(request, "Profile information updated")
        return HttpResponseRedirect(reverse("home:profile"))

@login_required
def post_comment(request, destination_id):
    destination = get_object_or_404(Destination, pk=signer.unsign(destination_id))
    if request.method == "POST":
        comment = request.POST.get("comment")
        commment_object = Comment.objects.create(
            message=comment,
            commenter=request.user
        )
        destination.comments.add(commment_object)
        return HttpResponseRedirect(reverse("home:destination_details", kwargs={'destination_id':destination_id}))
    return HttpResponse("Invalid Method")

@login_required
def delete_comment(request, destination_id,comment_id):
    comment = get_object_or_404(Comment, pk=signer.unsign(comment_id))
    # only users comment can be deleted
    if comment.commenter.id == request.user.id:
        comment.delete()
    return HttpResponseRedirect(reverse("home:destination_details", kwargs={'destination_id':destination_id}))


@login_required
def post_rate(request, destination_id):
    destination = get_object_or_404(Destination, pk=signer.unsign(destination_id))
    if request.method == "POST":
        #check if user already rated
        try:
            rating = UserRating.objects.get(destination=destination, user=request.user)
            messages.error(request, "You already rated this destination")
            return HttpResponseRedirect(reverse("home:destination_details", kwargs={'destination_id':destination_id}))
        except UserRating.DoesNotExist:
            rate = request.POST.get('rate')
            if not int(rate) > 0:
                messages.error(request, "Please select a number of star to rate")
                return HttpResponseRedirect(
                    reverse("home:destination_details", kwargs={'destination_id': destination_id}))
            UserRating.objects.create(
                destination=destination,
                user=request.user,
                rating=int(rate)
            )
            messages.success(request, "Your rating has been successfully submitted")
            return HttpResponseRedirect(reverse("home:destination_details", kwargs={'destination_id':destination_id}))

    return HttpResponse("Invalid method")


def category(request):
    categories = Category.objects.all()
    context = {
        'categories':categories
    }
    return render(request, 'home/category.html', context)


def search_destination(request):
    filter = request.GET.get('filter')
    destinations = []
    if filter:
        destinations = Destination.objects.filter(title__contains=filter)
    else:
        destinations = Destination.objects.all()
    context = {
        'destinations':destinations
    }
    return render(request, 'home/search_destination.html', context)

@login_required
def report_comment(request, destination_id, comment_id):
    comment = get_object_or_404(Comment, pk=signer.unsign(comment_id))
    if request.method == "POST":
        reason = request.POST.get("reason")
        ReportComment.objects.create(
            comment=comment,
            reason=reason,
            report_by=request.user
        )
        messages.success(request, "Comment has been reported")
        return HttpResponseRedirect(reverse("home:destination_details", kwargs={'destination_id':destination_id}))
    context = {
        'comment': comment
    }
    return render(request, 'home/report_comment.html', context)

def verify_email(request, verification_token):
    user = get_object_or_404(User, email_verification_token=verification_token)
    if not user.email_verified:
        user.email_verified = True
        user.save()
    context = {
        'user':user,
    }
    return render(request, 'home/verify_email.html',context)

@login_required
def reaction(request, destination_id, reaction):
    destination = get_object_or_404(Destination, pk=signer.unsign(destination_id))

    is_reacted = destination.reactions.filter(user=request.user).count()
    if is_reacted > 0:
        my_reaction = destination.reactions.filter(user=request.user).first()
        destination.reactions.remove(my_reaction)

    react = Reaction.objects.create(
        user = request.user,
        reaction = reaction,
    )
    destination.reactions.add(react)
    messages.success(request, "Reaction submitted")
    return HttpResponseRedirect(reverse("home:destination_details", kwargs={'destination_id': destination_id}))


def content_creator(request):
    return render(request, 'home/content_creator.html',{})

def about(request):
    return render(request, 'home/about.html',{})

templates/home/about.html
{% extends 'home/base.html' %}

{% block content %}
<br>
<h2>About</h2>
<p>&ldquo;<strong>Traveling</strong> &ndash; <em>it leaves you speechless, then turns you into a storyteller</em>&rdquo; &ndash; Ibn Battuta</p>
<p>The <strong>MUSEO Tu&rsquo; Agusan</strong> is part of the EduTourism program of Agusan del Sur State College of Agriculture and Technology, it is an online museum that serves as a virtual guide for local tourists in exploring the different attractions found in the province of Agusan del Sur.</p>
<p>Its purpose is to help YOU appreciate and discover the unseen beauty of Agusan del Sur. Your beautiful journey to Agusan, begins now! It is just a click away.</p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock %}

templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.ico' %}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Krona+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    {% block head_script %}
    {% endblock %}
  <style>
.star_coding {
  color: orange;
}
</style>
    {% block style %}

    {% endblock %}

    <title>MUSEO Tu' Agusan | Virtual Edu-Tourism</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'home:home' %}">MUSEO Tu' Agusan</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:destination' %}">Destinations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:category' %}">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:content_creator' %}">Be a content creator</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'home:search_destination' %}">
          <input class="form-control mr-sm-2" name="filter" type="search" placeholder="Search place..." aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search </button>
        </form>
        {% if request.user.is_authenticated %}
          <div class="btn-group ml-2">
          <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            Me
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'home:profile' %}">Profile</a>
<!--            <a class="dropdown-item" href="#">Notification</a>-->
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-outline-info my-2 my-sm-0 ml-2">Login</a>
        {% endif %}
      </div>
      </div>
    </nav>

       {% if messages %}
          <br>
            <div class="container">
        {% for message in messages %}
          {% if message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% elif message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
           {% elif message.tags == "warning" %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      </div>
        {% endif %}

    <div class="container" id="app">
      {% block content %}

      {% endblock %}
    </div>



    <!-- Footer -->
<footer class="page-footer font-small bg-dark text-white pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
<!--    <div class="row text-center text-md-left mt-3 pb-3">-->

<!--      &lt;!&ndash; Grid column &ndash;&gt;-->
<!--      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">-->
<!--        <h6 class="text-uppercase mb-4 font-weight-bold">Company name</h6>-->
<!--        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.-->
<!--          In nunc massa, fringilla vitae metus ac, tempor tristique sapien.-->
<!--          Proin tincidunt est vel odio gravida commodo. Ut id placerat massa.</p>-->
<!--      </div>-->
<!--      &lt;!&ndash; Grid column &ndash;&gt;-->

<!--      <hr class="w-100 clearfix d-md-none">-->

<!--      &lt;!&ndash; Grid column &ndash;&gt;-->
<!--      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">-->
<!--        <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>-->
<!--        <p>-->
<!--          <a href="#!">MDBootstrap</a>-->
<!--        </p>-->
<!--        <p>-->
<!--          <a href="#!">MDWordPress</a>-->
<!--        </p>-->
<!--        <p>-->
<!--          <a href="#!">BrandFlow</a>-->
<!--        </p>-->
<!--        <p>-->
<!--          <a href="#!">Bootstrap Angular</a>-->
<!--        </p>-->
<!--      </div>-->
<!--      &lt;!&ndash; Grid column &ndash;&gt;-->

<!--      <hr class="w-100 clearfix d-md-none">-->

<!--      &lt;!&ndash; Grid column &ndash;&gt;-->
<!--      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">-->
<!--        <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>-->
<!--        <p>-->
<!--          <a href="#!">Your Account</a>-->
<!--        </p>-->
<!--        <p>-->
<!--          <a href="#!">Become an Affiliate</a>-->
<!--        </p>-->
<!--        <p>-->
<!--          <a href="#!">Shipping Rates</a>-->
<!--        </p>-->
<!--        <p>-->
<!--          <a href="#!">Help</a>-->
<!--        </p>-->
<!--      </div>-->

<!--      &lt;!&ndash; Grid column &ndash;&gt;-->
<!--      <hr class="w-100 clearfix d-md-none">-->

<!--      &lt;!&ndash; Grid column &ndash;&gt;-->
<!--      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">-->
<!--        <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>-->
<!--        <p>-->
<!--          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>-->
<!--        <p>-->
<!--          <i class="fas fa-envelope mr-3"></i> info@gmail.com</p>-->
<!--        <p>-->
<!--          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>-->
<!--        <p>-->
<!--          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>-->
<!--      </div>-->
<!--      &lt;!&ndash; Grid column &ndash;&gt;-->

<!--    </div>-->
    <!-- Footer links -->

    <hr>

    <!-- Grid row -->
    <div class="row d-flex align-items-center">

      <!-- Grid column -->
      <div class="col-md-7 col-lg-8">

        <!--Copyright-->
        <p class="text-center text-md-left">© 2020 Copyright:
            <strong> Capstone Project</strong>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 ml-lg-0">

        <!-- Social buttons -->
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->

  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>



   {% block script %}
    {% endblock %}

  </body>
</html>

templates/home/category.html
{% extends 'home/base.html' %}

{% block content %}
<br>
<div class="row no-gutters">
  {% for category in categories %}
  <div class="col-md-4 p-2" >
    <div class="card d-flex flex-row " style="height:80px">
      <div class="w-25 bg-dark" style="{{category.bg_css}}">
<!--    https://cssgradient.io/gradient-backgrounds/    -->
      </div>
      <div class="w-75 d-flex justify-content-center align-items-center" >
          <h4 class="text-muted">{{category}}</h4>
      </div>
      <a href="{% url 'home:destination' %}?category={{category}}" class="stretched-link"></a>
    </div>
  </div>
  {% endfor %}
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/home/content_creator.html
{% extends 'home/base.html' %}

{% block content %}
<br>
<h2>Be a content creator</h2>
<br>
<div class="card card-body">
    <p><strong>Contact us thru :</strong></p>
    <p><strong>Email</strong> : <a href="mailto:banzonroleen@gmail.com">banzonroleen@gmail.com</a></p>
    <p><strong>Phone</strong> : 09387031621</p>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock %}

templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}
<br>
<div class="mb-4 bg-dark text-white p-3 rounded" style="background-image: linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0.34807426388524154) 100%), url('https://img.freepik.com/premium-vector/geometric-ethnic-oriental-seamless-pattern-traditional-design-background-carpet-wallpaper-clothing-wrapping-batik-fabric-vector-illustration-embroidery-style_71775-1403.jpg?w=996');">
  <h1 class="display-4 text-white">Welcome to MUSEO Tu' Agusan; <br> Virtual Edu-Tourism!</h1>
    <p class="lead">Maintain and Understand the Significant
        Expression of Our Culture Tu’ Agusan
    </p>
  <hr class="my-4">
  <a class="btn btn-outline-danger btn-lg" href="{% url 'home:about' %}" role="button">Learn more</a>
    
</div>

<br>

<h3 class="text-muted mb-3">Categories you might like</h3>
<div class="row no-gutters">
  {% for category in categories %}
  <div class="col-md-4 p-2" >
    <div class="card d-flex flex-row " style="height:80px">
      <div class="w-25 bg-dark" style="{{category.bg_css}}">
<!--    https://cssgradient.io/gradient-backgrounds/    -->
      </div>
      <div class="w-75 d-flex justify-content-center align-items-center" >
          <h4 class="text-muted">{{category}}</h4>
      </div>
      <a href="{% url 'home:destination' %}?category={{category}}" class="stretched-link"></a>
    </div>
  </div>
  {% endfor %}
</div>


<br>
<br>
<h3 class="text-muted mb-3">Featured Destination</h3>

<div class="row">
{% for featured in featured_destination %}
    <div class="col-md-4">

      <div class="card mb-4">
      <img src="{{featured.destination.first_image}}" class="card-img-top" alt="...">
      <div class="card-body">
        <p><strong>{{featured.destination.title}}</strong></p>
        <p class="card-text">{{featured.destination.short_description|safe}}</p>
        <p class="card-text"><small class="text-muted">{{featured.destination.get_react_count}} Reactions | {{featured.destination.num_comments}} Comments</small></p>
      <a href="{% url 'home:destination_details' destination_id=featured.destination.getEncryptedID %}" class="stretched-link"></a>
      </div>

    </div>
  </div>
{% endfor %}
  </div>

{% endblock %}

templates/home/profile.html
{% extends 'home/base.html' %}

{% block content %}

<br>
<div class="shadow bg-white rounded">
  <div class="row no-gutters">
    <div class="col-md-4 bg-dark">
      <div class="p-4 text-center ">
        <img src="https://i2.wp.com/airlinkflight.org/wp-content/uploads/2019/02/male-placeholder-image.jpeg?ssl=1" width="150px" height="150px" class="rounded mx-auto d-block" alt="...">
        <h3 class="mt-3 text-white">{{request.user.get_full_name}}</h3>
        <p class="text-white">{{request.user.username}}</p>

<!--          <button type="button" class="btn btn-sm btn-outline-success">Edit</button>-->
          <a href="{% url 'home:change_password' %}" class="btn btn-sm btn-outline-danger">Change password</a>
         <a href="/admin" class="btn btn-sm btn-outline-warning">Tag your location</a>

      </div>
    </div>
    <div class="col-md-8">
      <div class="p-4">

        <form method="post">
          {% csrf_token %}
        <h3 class="text-warning">Information</h3>
        <hr>

          {% for key, value  in profile_info.items %}

            <div class="row mt-2">
              <div class="col-md-3">
                <strong>{{key}}</strong>
              </div>
              <div class="col-md-9">
                <input type="text" name="{{key}}" placeholder="{{value.placeholder}}" class="form-control form-control-sm" {% if key == "Email" %} disabled {% endif %} value="{{value.value}}"/>
              </div>
            </div>

          {% endfor %}

      <button type="submit" class="mt-3 pull-right btn btn-outline-dark">Update</button>
          <br>
          <br>
        </form>
      </div>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>



{% endblock %}